environment:
  test_browserstack_api_username:
    secure: Dlz0haYgc/lPE/oJGqXnVA==
  test_browserstack_api_accesskey:
    secure: o5Lwx3DV65G1zekin6kUNik5BCpCwV7I6FwbvmLXZ6k=
    
#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Script build.cake -Target AppVeyor -Verbosity Diagnostic --settings_skipverification=true

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/
    
deploy:
  provider: NuGet
  api_key:
    secure: oy2mybeb5er42ndce3datul5lyvxfnlexg3m2n25onttiq
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
